# Generated by Django 2.0.4 on 2018-05-02 22:49

from django.db import migrations, models
import django.utils.timezone
import horizon.main
import horizon.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email地址')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('business_name', models.CharField(default='', max_length=100, verbose_name='商户名称')),
                ('brand', models.CharField(default='', max_length=60, verbose_name='所属品牌')),
                ('manager', models.CharField(default='', max_length=20, verbose_name='经理人姓名')),
                ('mall_id', models.IntegerField(default=0, verbose_name='购物中心ID')),
                ('address', models.CharField(max_length=128, verbose_name='地理位置')),
                ('hotline', models.CharField(max_length=16, null=True, verbose_name='店铺联系电话')),
                ('logo_url', models.CharField(default='', max_length=200, verbose_name='头像')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(max_length=32, verbose_name='维度')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
            options={
                'db_table': 'fm_auth_user',
            },
            bases=(horizon.mixins.BaseModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IdentifyingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('identifying_code', models.CharField(max_length=6, verbose_name='验证码')),
                ('expires', models.DateTimeField(default=horizon.main.minutes_5_plus, verbose_name='过期时间')),
            ],
            options={
                'db_table': 'fm_identifying_code',
                'ordering': ['-expires'],
            },
            bases=(horizon.mixins.BaseModelMixin, models.Model),
        ),
    ]